accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views # diff from other views
from . import views


app_name = 'accounts'

urlpatterns = [
    url(r'login/$',
    auth_views.LoginView.as_view(template_name='accounts/login.html'),
    name='login'),
    url(r'logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'signup/$', views.SignUp.as_view(), name='signup')
]

posts/urls.py
from django.conf.urls import url

from . import views
app_name = 'posts'

urlpatterns = [
    url(r'^$', views.PostList.as_view(), name='all'),
    url(r'new/$', views.CreatePost.as_view(), name='create'),
    url(r'by/(?P<username>[-\w]+)/$', views.UserPosts.as_view(), name='for_user'),
    url(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.PostDetail.as_view(), name='single'),
    url(r'delete/(?P<pk>\d+)/$', views.DeletePost.as_view(), name='delete')
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts') ),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^test/$', views.TestPage.as_view(), name='test'),
    url(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
    url(r'^posts', include('posts.urls', namespace='posts')),
    url(r'^groups/', include('groups.urls', namespace='groups')),
    url(r'^agriculture/$', views.AgriculturePage.as_view(), name='agriculture'),
    url(r'^wildanimals/$', views.WildAnimalsPage.as_view(), name='wildanimals'),
    url(r'^wildfruits/$', views.WildFruitsPage.as_view(), name='wildfruits'),
]

templates/agriculture.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <p>Rusanhi Agriculture</p>

  <table cellpadding="40" cellspacing="20">
  <tr>
      <td><img src="{% static "pics\agriculture\mazhanje.jpeg" %}"
        onmouseover="this.src='{% static "pics\agriculture\matohwe.jpeg" %}'" onmouseout="this.src='{% static "pics\agriculture\mazhanje.jpeg" %}'"
        alt="Can't find pic" width="250" height="auto"></td>

      <td><img src="{% static "pics\agriculture\nwiwa.jpeg" %}"
        onmouseover="this.src='{% static "pics\agriculture\tomatoes.jpeg" %}'" onmouseout="this.src='{% static "pics\agriculture\nwiwa.jpeg" %}'"
        alternate="Can't find pic" width="250" height="auto"></td>

      <td><img src="{% static "pics\agriculture\pineapple.jpeg" %}"
        onmouseover="this.src='{% static "pics\agriculture\nhunguru.jpeg" %}'" onmouseout="this.src='{% static "pics\agriculture\pineapple.jpeg" %}'"
        alternate="Can't find pic" width="250" height="auto"></td>
</tr>
  </table>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Rusanhi</title>

    <!-- Boostrap Theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

      <!-- Optional theme -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

      <!-- Latest compiled and minified JavaScript -->
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


      <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

      <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">
  </head>
  <body>

    <!-- # Navigation bar -->
    <nav class='navbar mynav' role='navigation' id='navbar'>
      <div class="container">
        <!-- Link to home page -->
        <a class='navbar-brand mynav' href="{% url 'home' %}">Rusanhi</a>

        <!-- Right align content of navbar -->
        <ul class='nav navbar-nav navbar-right'>

        <!-- Check if user is aunthenticated, then allow the following -->
        {% if user.is_authenticated %}
          <li> <a href="{% url 'posts:create' %}">Post</a> </li>
          <li> <a href="{% url 'groups:all' %}">Groups</a> </li>
          <li> <a href="{% url 'groups:create' %}">Create Group</a> </li>
          <li> <a href="{% url 'accounts:logout' %}">Log Out</a> </li>

          <!-- if user is not aunthenticated, allow only the following-->
          {% else %}
          <li><a target="_blank" href="simplesocial/templates/wildanimals.html">Wild Animals</a> </li>
            <li><a href="#">Wild Fruits</a> </li>
            <li><a href="#">Agriculture</a></li>
            <li> <a href="{% url 'groups:all' %}">Groups</a> </li>
            <li> <a href="{% url 'accounts:login' %}">Log In</a> </li>
            <li> <a href="{% url 'accounts:signup' %}">Sign Up</a> </li>

          {% endif %}
        </ul>

      </div>

    </nav>
      <div class="container mycontent">

        {% block content %}

        {% endblock %}
      </div>

  </body>

</html>

templates/index.html
{% extends "base.html" %}
{% load static %}


{% block content %}
  <h1>Welcome to Rusanhi Development Association!</h1>
  <!-- <a target="_blank" href='https://www.facebook.com/'><i class='fa fa-facebook'>Facebook</i></a> -->
  <p></p>
  <!-- <video controls src="{% static "pics\videos\road_is_required.mp4"%}" type="video/mp4" autoplay poster="posterimage.jpg"></video> -->
  <style media="screen">
    table{
      width: 750px;
      border: 5px solid red;
      cellspacing: 40px;
    }
  </style>

  <p>Road ingodiwa anhuwe! Ngatishandei tiwake yedu!</p>
  <a target="_blank" align=center href= "templates/wildanimals.html" target="_blank">Animals</a>

  <table>
  <tr>
      <td><img src="{% static "pics\people\vanhu_madzimai.jpeg" %}"
        onmouseover="this.src='{% static "pics\sportsedu\bhora.jpeg" %}'" onmouseout="this.src='{% static "pics\people\vanhu_madzimai.jpeg" %}'"
        alt="Can't find pic" width="250" height="auto"></td>

      <td><img src="{% static "pics\people\rural_bus.jpeg" %}"
        onmouseover="this.src='{% static "pics\landscape\view2.jpg" %}'" onmouseout="this.src='{% static "pics\people\rural_bus.jpeg" %}'"
        alternate="Can't find pic" width="250" height="auto"></td>

      <td><img src="{% static "pics\wildanimals\leopard.jpg" %}"
        onmouseover="this.src='{% static "pics\wildanimals\Ngwarati.jpg" %}'" onmouseout="this.src='{% static "pics\wildanimals\leopard.jpg" %}'"
        alternate="Can't find pic" width="250" height="auto"></td>
</tr>
  </table>

  <p></p>

  <table>
    <tr>
        <td><a href='#' target="_blank">Mutasa Rural District Council</a></td>

        <td><a href="http://www.maphill.com/zimbabwe/manicaland/mutasa/" target="_blank">Maps of Mutasa</a></td>

      <td><a href="https://www.citypopulation.de/php/zimbabwe-admin.php?adm2id=106" target="_blank">Mutasa Population</a></td>
    <td><a href="https://www.facebook.com/mutasardc/" target="_blank">Mutasa on Facebook</a></td>

    </tr>
</table>
{% endblock %}

templates/test.html
{% extends 'base.html' %}

{% block content %}

  <h1>You are now logged in!</h1>

{% endblock %}

templates/thanks.html
{% extends 'base.html' %}

{% block content %}

  <h1>Thanks for visiting, come back soon!</h1>

{% endblock %}

templates/trust_members.html
{% extends 'base.html'%}
{% load static %}

{% block content %}

<p>Rusanhi Trust Members</p>
<div class="">


  <a target="_blank" href='https://www.facebook.com/'><i class='fa fa-facebook'>Tichaona Chinzou - Chairman</i></a>
  <a href='#'><i class='fa fa-google-plus'></i></a>
  <a href='https://twitter.com/home'><i class='fa fa-twitter'></i></a>

  <a target="_blank" href='https://www.facebook.com/'><i class='fa fa-facebook'>Terence Wilson Mudangwe</i></a>
  <a href='#'><i class='fa fa-google-plus'></i></a>
  <a href='#'><i class='fa fa-twitter'></i></a>

  <a target="_blank" href='https://www.facebook.com/'><i class='fa fa-facebook'>Godwin Kudumba</i></a>
  <a href='#'><i class='fa fa-google-plus'></i></a>
  <a href='#'><i class='fa fa-twitter'></i></a>

  <a target="_blank" href='https://www.facebook.com/'><i class='fa fa-facebook'>Willie Gonda</i></a>
  <a href='#'><i class='fa fa-google-plus'></i></a>
  <a href='#'><i class='fa fa-twitter'></i></a>

  <a target="_blank" href='https://www.facebook.com/'><i class='fa fa-facebook'>Oscar Chipangura</i></a>
  <a href='#'><i class='fa fa-google-plus'></i></a>
  <a href='#'><i class='fa fa-twitter'></i></a>

  <a target="_blank" href='https://www.facebook.com/'><i class='fa fa-facebook'>Francis Katsuwa</i></a>
  <a href='#'><i class='fa fa-google-plus'></i></a>
  <a href='#'><i class='fa fa-twitter'></i></a>

  <a target="_blank" href='https://www.facebook.com/'><i class='fa fa-facebook'>Francis Pasipanodya</i></a>
  <a href='#'><i class='fa fa-google-plus'></i></a>
  <a href='#'><i class='fa fa-twitter'></i></a>

  <a target="_blank" href='https://www.facebook.com/'><i class='fa fa-facebook'>Peter Matsanura</i></a>
  <a href='#'><i class='fa fa-google-plus'></i></a>
  <a href='#'><i class='fa fa-twitter'></i></a>
</div>

{% endblock %}

<!--


10) Peter Matsanura -->

templates/wildanimals.html
{% extends base.html %}
{% load static %}

{% block content %}
  <p>Wild Animals in Rusanhi</p>

  <table cellpadding="40" cellspacing="20">
    <tr>
        <td><img src="{% static "pics\wildanimals\gudo.jpeg" %}"
          onmouseover="this.src='{% static "pics\wildanimals\leopard.jpeg" %}'" onmouseout="this.src='{% static "pics\wildanimals\gudo.jpeg" %}'"
          alt="Can't find pic" width="250" height="auto"></td>

        <td><img src="{% static "pics\wildanimals\Ngwarati.jpeg" %}"
          onmouseover="this.src='{% static "pics\wildanimals\gudo.jpeg" %}'" onmouseout="this.src='{% static "pics\wildanimals\Ngwarati.jpeg" %}'"
          alternate="Can't find pic" width="250" height="auto"></td>

          <td><img src="{% static "pics\wildanimals\leopard.jpg" %}"
            onmouseover="this.src='{% static "pics\wildanimals\Ngwarati.jpg" %}'" onmouseout="this.src='{% static "pics\wildanimals\leopard.jpg" %}'"
            alternate="Can't find pic" width="250" height="auto"></td>
    </tr>
  </table>

{% endblock %}

templates/wildfruits.html
{%  extends "base.html" %}

{% load static %}

{% block content %}

  <table>
    <tr>
      <td> <img src="{% static "pics\wildfruits\nwiwa.jpeg" %}"
        onmouseover="this.src='{% static "pics\wildfruits\nhunguru.jpeg" %}'"
        onmouseout="this.src='{% static "pics\wildfruits\nwiwa.jpeg" %}'"
        alt="Can't find pic!"></td>

        <td>,<img src="{% static "pics\wildfruits\mazhanje.jpeg" %}"
          onmouseover="this.src='{% static "pics\wildfruits\pineapple.jpeg" %}'"
          onmouseout="this.src='{% static "pics\wildfruits\mazhanje.jpeg" %}'"
          alt="Can't find pic!"></td>

          <td>,<img src="{% static "pics\wildfruits\tomatoes.jpeg" %}"
            onmouseover="this.src='{% static "pics\wildfruits\matohwe.jpeg" %}'"
            onmouseout="this.src='{% static "pics\wildfruits\tomatoes.jpeg" %}'"
            alt="Can't find pic!"></td

    </tr>
  </table>

{% endblock %}